### ISSUE TITLE
QRCode type

### ISSUE THREAD

**Issue by carstenbauer** [JuliaImages/QRCoders.jl#2]
Hi there, great package!

Given the discussion in https://discourse.julialang.org/t/ann-qrcode-jl-create-qr-code-within-julia/26923 we probably want to add support for plotting to SVG, PDF, or the REPL itself!

I think it makes sense to define a QRCode type, which basically just wraps the current `BitArray`. This allows us to dispatch on QR codes and, for example, modify their `show` behavior.

What are your thoughts on this?

**Comment by RexWzh** [comment]
I think this issue can be closed now. 

Good suggestion for the `QRCode` type and `REPL` plot things! @carstenbauer 
They are in the current version after https://github.com/JuliaImages/QRCoders.jl/pull/35.
