### ISSUE TITLE
Suggestion: unicode pixel output

### ISSUE THREAD

**Issue by notinaboat** [JuliaImages/QRCoders.jl#25]
A little hack to show a QRCode on the terminal with two pixels per terminal row.

```julia
julia> pixel_char(x) = all(x) ? '█' : x[1] ? '▀' : x[2] ? '▄' : ' '
julia> qr_string(d) = join((String(pixel_char.(eachcol(d[i:i+1,:]))) for i in 1:2:d.dims[1]-1), "\n")
julia> qrcode("http://julialang.org") |> qr_string |> print
                                 
                                 
    █▀▀▀▀▀█ ▄ ▀▄ ▄█   █▀▀▀▀▀█    
    █ ███ █ █▀█▄█▄▀▄█ █ ███ █    
    █ ▀▀▀ █  █▄▄█▄▀ ▄ █ ▀▀▀ █    
    ▀▀▀▀▀▀▀ █ ▀▄▀ ▀▄█ ▀▀▀▀▀▀▀    
    ▀▄▄▄ ▄▀ █▀▀ █▀██ ▀▀▄▄███     
    ▄█▄▀▄ ▀▀ ▄▄▄▀▀██▄▀▄█ █ ▀█    
    █▄██▀▄▀█▀█▄▀▄█▀▄█ ▀▄   ▄▀    
    █ ▀█▀▄▀█▄▀  ▄██▀█▄▄ ▀▀▄▀█    
    ▀ ▀▀  ▀▀█ ▄ ▀ ▀▀█▀▀▀█ █      
    █▀▀▀▀▀█  ██▄▀▀█▄█ ▀ █▀  █    
    █ ███ █  ██▀▄▄ ▀███▀▀█▀██    
    █ ▀▀▀ █  ▀▄ ▄█▀ █ ▄█▄ ▀ █    
    ▀▀▀▀▀▀▀ ▀▀ ▀▀▀  ▀ ▀  ▀  ▀    
```

**Comment by inokawazu** [comment]
Looks nice, I can confirm it works as a QR Code! I would wonder it is possible to adjust the aspect ratio to approximate 1:1.

**Comment by notinaboat** [comment]
The aspect ratio depends mostly on the terminal font.

On my 7" Raspberry Pi touch screen using the default linux terminal font it looks pretty good...

 
![IMG_6555](https://user-images.githubusercontent.com/73502641/190966517-ab8153e3-b43f-4f76-b375-d64d8ada7743.jpeg)

**Comment by inokawazu** [comment]
@notinaboat, sorry, yes this must be a GitHub issue with their fonts ig. I can confirm to get 1:1 on my Linux box's terminal. Looks good imo.

**Comment by RexWzh** [comment]
Great!! I like the idea.
It looks nice in my device (Ubuntu).  This can be added as part of the style plan.

I just try some other Unicode, but had a worse behavior. :sweat:
```jl
julia> join(Char.(0x25A0:0x25af), ' ')
"■ □ ▢ ▣ ▤ ▥ ▦ ▧ ▨ ▩ ▪ ▫ ▬ ▭ ▮ ▯"
```
```jl
pixelchar(x::Integer) = Char(0x25a0 + x)
pixelchar(line::AbstractVector) = join(pixelchar.(line), ' ')
qrstring(mat) = join(pixelchar.(eachrow(mat)), '\n')
qrstring(qrcode("Hello world!")) |> print
```
output:
```jl
□ □ □ □ □ □ □ ■ ■ ■ ■ □ ■ ■ □ □ □ □ □ □ □
□ ■ ■ ■ ■ ■ □ ■ □ ■ □ □ ■ ■ □ ■ ■ ■ ■ ■ □
□ ■ □ □ □ ■ □ ■ ■ □ □ □ ■ ■ □ ■ □ □ □ ■ □
□ ■ □ □ □ ■ □ ■ ■ ■ ■ □ □ ■ □ ■ □ □ □ ■ □
□ ■ □ □ □ ■ □ ■ □ □ ■ □ □ ■ □ ■ □ □ □ ■ □
□ ■ ■ ■ ■ ■ □ ■ ■ □ □ □ ■ ■ □ ■ ■ ■ ■ ■ □
□ □ □ □ □ □ □ ■ □ ■ □ ■ □ ■ □ □ □ □ □ □ □
■ ■ ■ ■ ■ ■ ■ ■ ■ □ □ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■
□ ■ □ ■ □ ■ □ ■ ■ ■ ■ ■ □ ■ ■ ■ □ ■ ■ □ ■
□ □ □ □ □ □ ■ ■ ■ ■ ■ □ ■ ■ □ □ □ ■ ■ □ □
□ □ □ ■ ■ ■ □ ■ □ □ □ □ ■ □ ■ □ □ □ □ □ □
■ □ ■ ■ ■ □ ■ □ ■ □ □ □ □ ■ ■ ■ □ ■ ■ □ ■
■ □ ■ □ □ □ □ ■ ■ ■ ■ □ ■ □ ■ □ □ ■ ■ ■ ■
■ ■ ■ ■ ■ ■ ■ ■ □ □ ■ □ ■ □ ■ ■ ■ ■ □ □ ■
□ □ □ □ □ □ □ ■ ■ ■ □ ■ □ ■ ■ □ □ ■ □ □ □
□ ■ ■ ■ ■ ■ □ ■ ■ □ □ ■ ■ ■ ■ □ ■ ■ ■ □ ■
□ ■ □ □ □ ■ □ ■ □ ■ □ ■ □ ■ ■ ■ □ ■ ■ □ ■
□ ■ □ □ □ ■ □ ■ ■ □ □ □ □ ■ □ □ □ ■ □ □ ■
□ ■ □ □ □ ■ □ ■ □ ■ □ ■ □ ■ □ ■ □ ■ □ ■ □
□ ■ ■ ■ ■ ■ □ ■ ■ □ ■ □ ■ ■ ■ ■ □ ■ ■ □ ■
□ □ □ □ □ □ □ ■ □ ■ ■ □ □ ■ ■ □ ■ ■ ■ □ □
```

It looks better when replacing `0x25A0` by `0x2b1c`(■ □ by ⬛⬜)
```jl
pixelchar(x::Integer) = Char(0x2b1c - x)
pixelchar(line::AbstractVector) = join(pixelchar.(line))
qrstring(qrcode("Hello world!"; compact=false)) |> print
```

It looks well it my device(though the size is too large)
![image](https://user-images.githubusercontent.com/62223937/191031632-4af3c223-0c99-431b-88b0-82cc43112a39.png)

**Comment by RexWzh** [comment]
> A little hack to show a QRCode on the terminal with two pixels per terminal row.
> 
> ```julia
> julia> pixel_char(x) = all(x) ? '█' : x[1] ? '▀' : x[2] ? '▄' : ' '
> julia> qr_string(d) = join((String(pixel_char.(eachcol(d[i:i+1,:]))) for i in 1:2:d.dims[1]-1), "\n")
> julia> qrcode("http://julialang.org") |> qr_string |> print
>                                  
>                                  
>     █▀▀▀▀▀█ ▄ ▀▄ ▄█   █▀▀▀▀▀█    
>     █ ███ █ █▀█▄█▄▀▄█ █ ███ █    
>     █ ▀▀▀ █  █▄▄█▄▀ ▄ █ ▀▀▀ █    
>     ▀▀▀▀▀▀▀ █ ▀▄▀ ▀▄█ ▀▀▀▀▀▀▀    
>     ▀▄▄▄ ▄▀ █▀▀ █▀██ ▀▀▄▄███     
>     ▄█▄▀▄ ▀▀ ▄▄▄▀▀██▄▀▄█ █ ▀█    
>     █▄██▀▄▀█▀█▄▀▄█▀▄█ ▀▄   ▄▀    
>     █ ▀█▀▄▀█▄▀  ▄██▀█▄▄ ▀▀▄▀█    
>     ▀ ▀▀  ▀▀█ ▄ ▀ ▀▀█▀▀▀█ █      
>     █▀▀▀▀▀█  ██▄▀▀█▄█ ▀ █▀  █    
>     █ ███ █  ██▀▄▄ ▀███▀▀█▀██    
>     █ ▀▀▀ █  ▀▄ ▄█▀ █ ▄█▄ ▀ █    
>     ▀▀▀▀▀▀▀ ▀▀ ▀▀▀  ▀ ▀  ▀  ▀    
> ```

Thanks for the suggestion@notinaboat . It is now as an implementation in `style.jl`.
